POST http://localhost:8081/user/signup
Content-Type: application/json 

{
    "username" : "tochiamanze",
    "email" : "cdon@gmail.com",
    "password" : "tochi12345"
}

###

POST http://localhost:8081/user/login
Content-Type: application/json 

{
    "username" : "tochiamanze",
    "password" : "tochi12345"
}

###
GET http://localhost:8081/user/getAll
Content-Type: application/json

###EditUser1
POST http://localhost:8081/user/editUser
Content-Type: application/json 

{
    "userId" : "643ea2dc32e9b85c5aa70c5e",
    "favline" : "Red",
    "favroute" : "Green"
}

###EditUser2
POST http://localhost:8081/user/editUser
Content-Type: application/json 

{
    "userId" : "643ea2dc32e9b85c5aa70c5e",
    "favline" : "Purple",
    "favroute" : "Blue"
}

###
GET  http://localhost:8081/user/getUserById
Content-Type: application/json 

{
    "userId" : "635ab8dfc407faf9f73deaf1"
}

###
GET  http://localhost:8081/user/getUserById
Content-Type: application/json 

{
    "userId" : "634edb2a16710b2cda6fb370"
}

###
POST  http://localhost:8081/user/deleteAll


###
POST http://localhost:8081/tickets/createTickets
Content-Type: application/json 

{
    "username" : "ThomasUrb",
    "departuretime" : "11:00",
    "stationA" : "StationA",
    "stationB" : "StationB"

}

###
GET http://localhost:8081/tickets/getAllTickets
Content-Type: application/json

###
GET http://localhost:8081/tickets/getTicketsbyUser?username=ThomasUrb
Content-Type: application/json

###
POST  http://localhost:8081/tickets/deleteTicket
Content-Type: application/json

### Change this number to any valid ticket number 
{
    "ticketnum" : "29472"
}
###
POST http://localhost:8081/userquestions/userInfoSecurity
Content-Type: application/json

{   "username": "ChiaSu",
    "color": "red",
    "animal":"dog",
    "country":"UK"
}


